//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryDBEntities1 : DbContext
    {
        public LibraryDBEntities1()
            : base("name=LibraryDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audiences> Audiences { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<BookToUser> BookToUser { get; set; }
        public virtual DbSet<BorrowedBooks> BorrowedBooks { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<KindsOfBooks> KindsOfBooks { get; set; }
        public virtual DbSet<ProfileBook> ProfileBook { get; set; }
        public virtual DbSet<ReadingBooks> ReadingBooks { get; set; }
        public virtual DbSet<StatusUser> StatusUser { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WishList> WishList { get; set; }
    }
}
