//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KindsOfBooksForUsers
    {
        public int CodeKindsOfBooksForUsers { get; set; }
        public string UserId { get; set; }
        public int KindBookCode { get; set; }
        public int Count { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
    
        public virtual KindsOfBooks KindsOfBooks { get; set; }
        public virtual Users Users { get; set; }
    }
}
