//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileBook
    {
        public int CodeProfileBook { get; set; }
        public int BookCode { get; set; }
        public int KindBook { get; set; }
        public int AudienceAge { get; set; }
        public int AudienceStatus { get; set; }
        public int AudienceGender { get; set; }
    
        public virtual ReadingBooks ReadingBooks { get; set; }
    }
}
