//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingBooks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReadingBooks()
        {
            this.BorrowedBooks = new HashSet<BorrowedBooks>();
            this.ProfileBook = new HashSet<ProfileBook>();
            this.BookToUser = new HashSet<BookToUser>();
            this.WishList = new HashSet<WishList>();
        }
    
        public int CodeBook { get; set; }
        public string NameBook { get; set; }
        public int AuthorCode { get; set; }
        public int KindBookCode { get; set; }
        public int AudienceCode { get; set; }
        public int LengthBook { get; set; }
        public bool IsBorrowed { get; set; }
        public int StatusCode { get; set; }
        public int GenderCode { get; set; }
        public string ImgBook { get; set; }
    
        public virtual Audiences Audiences { get; set; }
        public virtual Authors Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowedBooks> BorrowedBooks { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual KindsOfBooks KindsOfBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileBook> ProfileBook { get; set; }
        public virtual StatusUser StatusUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookToUser> BookToUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishList { get; set; }
    }
}
