//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusForUsers
    {
        public int CodeStatusForUsers { get; set; }
        public int StatusCode { get; set; }
        public int UserId { get; set; }
    
        public virtual StatusUser StatusUser { get; set; }
        public virtual Users Users { get; set; }
    }
}
