//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowedBooks
    {
        public long CodeBorrowedBooks { get; set; }
        public Nullable<long> BookCode { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> BorrowingDate { get; set; }
        public Nullable<bool> IsBorrowed { get; set; }
    
        public virtual ReadingBooks ReadingBooks { get; set; }
        public virtual Users Users { get; set; }
    }
}
