//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileBook
    {
        public long CodeProfileBook { get; set; }
        public long BookCode { get; set; }
        public Nullable<int> KindBook { get; set; }
        public Nullable<int> AudienceAge { get; set; }
        public Nullable<int> AudienceStatus { get; set; }
        public Nullable<int> AudienceGender { get; set; }
    
        public virtual ReadingBooks ReadingBooks { get; set; }
    }
}
