//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audiences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Audiences()
        {
            this.AudiencesForUsers = new HashSet<AudiencesForUsers>();
            this.ReadingBooks = new HashSet<ReadingBooks>();
        }
    
        public long CodeAudience { get; set; }
        public string KindAudience { get; set; }
        public int Age { get; set; }
        public Nullable<long> StatusCode { get; set; }
        public Nullable<long> GenderCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AudiencesForUsers> AudiencesForUsers { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual StatusUser StatusUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadingBooks> ReadingBooks { get; set; }
    }
}
