//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingBooks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReadingBooks()
        {
            this.BorrowedBooks = new HashSet<BorrowedBooks>();
            this.ProfileBook = new HashSet<ProfileBook>();
        }
    
        public long CodeBook { get; set; }
        public string NameBook { get; set; }
        public Nullable<long> AuthorCode { get; set; }
        public Nullable<long> KindBookCode { get; set; }
        public Nullable<long> AudienceCode { get; set; }
        public int LengthBook { get; set; }
        public Nullable<bool> IsBorrowed { get; set; }
    
        public virtual Audiences Audiences { get; set; }
        public virtual Authors Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowedBooks> BorrowedBooks { get; set; }
        public virtual KindsOfBooks KindsOfBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileBook> ProfileBook { get; set; }
    }
}
